version: '3.8'

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartlog-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - db

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: smartlog-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: smartlog-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: smartlog
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: smartlog
      MYSQL_PASSWORD: smartlog
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel

  # phpMyAdmin (for database management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smartlog-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - db

volumes:
  mysql_data:
    driver: local

networks:
  laravel:
    driver: bridge